select * from sysadm.clz_skrypty where system = 'K2000' and skrypt = 'S061221_0';


-- jeœli istnieje to przerwaæ
--BAZA=K2000;
--uzytkownik SYSADM;
--narzedzie SQLTALK;





insert into sysadm.CLZ_SKRYPTY (SYSTEM, SKRYPT, STATUS, DEVELOPER, OPER_MOD, OPIS, TESTER) 
values ('K2000_S','S061221_0', 'N', 'ACIESLA', USER, 'dodanie partycji dla tabel rozliczeniowych', 'ACIESLA');


ALTER TABLE SYSADM.KC_OU_FAKTURY 
  ADD PARTITION KC_OU_FAKTURY_ROK2007
  VALUES LESS THAN (2008 )
  TABLESPACE KC_LMT_2007_DATA_128
  INITRANS   1
  STORAGE (
      BUFFER_POOL     DEFAULT)
/

ALTER TABLE SYSADM.KC_OU_INNE_FAKTURY 
  ADD PARTITION KC_OU_INNE_FAKTURY_ROK2007
  VALUES LESS THAN (2008 )
  TABLESPACE KC_LMT_2007_DATA_4096
  INITRANS   1
  STORAGE (
      BUFFER_POOL     DEFAULT)
/

ALTER TABLE SYSADM.KC_OU_INNE_FAKTURY_EXT 
  ADD PARTITION KC_OU_INNE_FAKTURY_EXT_ROK2007
  VALUES LESS THAN (2008 )
  TABLESPACE KC_LMT_2007_DATA_4096
  INITRANS   1
  STORAGE (
      BUFFER_POOL     DEFAULT)
/

ALTER TABLE SYSADM.KC_OU_INNE_FAKTURY_OS 
  ADD PARTITION KC_OU_INNE_FAKTURY_OS_ROK2007
  VALUES LESS THAN (2008 )
  TABLESPACE KC_LMT_2007_DATA_4096
  INITRANS   1
  STORAGE (
      BUFFER_POOL     DEFAULT)
/

ALTER TABLE SYSADM.KC_OU_KONIEC 
  ADD PARTITION KC_OU_KONIEC_ROK2007
  VALUES LESS THAN (2008 )
  TABLESPACE KC_LMT_2006_DATA_128
  INITRANS   1
  STORAGE (
      BUFFER_POOL     DEFAULT)
/


ALTER TABLE SYSADM.KC_OU_POZ_SPRAW 
  ADD PARTITION KC_OU_POZ_SPRAW_ROK2007
  VALUES LESS THAN (2008 )
  TABLESPACE KC_LMT_2007_DATA_128
  INITRANS   1
  STORAGE (
      BUFFER_POOL     DEFAULT)
/

ALTER TABLE SYSADM.KC_OU_SPRAW 
  ADD PARTITION KC_OU_SPRAW_ROK2007
  VALUES LESS THAN (2008 )
  TABLESPACE KC_LMT_2007_DATA_128
  INITRANS   1
  STORAGE (
      BUFFER_POOL     DEFAULT)
/


ALTER TABLE SYSADM.KC_OU_WYK_APTEK 
  ADD PARTITION R2007_0
  VALUES LESS THAN (2008, '1' )
  TABLESPACE KC_LMT_2007_DATA_4096
  INITRANS   1
  STORAGE (
      BUFFER_POOL     DEFAULT)
/
	  
ALTER TABLE SYSADM.KC_OU_WYK_APTEK 
  ADD PARTITION R2007_1
  VALUES LESS THAN (2008, '2' )
  TABLESPACE KC_LMT_2007_DATA_4096
  INITRANS   1
  STORAGE (
      BUFFER_POOL     DEFAULT)
/

ALTER TABLE SYSADM.KC_OU_WYK_APTEK_EXT 
  ADD PARTITION R2007_0
  VALUES LESS THAN (2008, '1' )
  TABLESPACE KC_LMT_2007_DATA_4096
  INITRANS   1
  STORAGE (
      BUFFER_POOL     DEFAULT)
/

ALTER TABLE SYSADM.KC_OU_WYK_APTEK_EXT 
  ADD PARTITION R2007_1
  VALUES LESS THAN (2008, '2' )
  TABLESPACE KC_LMT_2007_DATA_4096
  INITRANS   1
  STORAGE (
      BUFFER_POOL     DEFAULT)
/

ALTER TABLE SYSADM.WRN_FINISH 
  ADD PARTITION R2007
  VALUES LESS THAN (2008 )
  TABLESPACE KC_LMT_2007_DATA_128
  INITRANS   1
  STORAGE (
      BUFFER_POOL     DEFAULT)
/


ALTER TABLE SYSADM.KC_KASY_IMP_SPR_E 
  ADD PARTITION R2007
  VALUES LESS THAN (2008 )
  TABLESPACE KC_LMT_2007_DATA_128
  INITRANS   1
  STORAGE (
      BUFFER_POOL     DEFAULT)
/

ALTER TABLE SYSADM.KC_KASY_IMP_SPR_OS 
  ADD PARTITION R2007
  VALUES LESS THAN (2008 )
  TABLESPACE KC_LMT_2007_DATA_128
  INITRANS   1
  STORAGE (
      BUFFER_POOL     DEFAULT)
/




update sysadm.CLZ_SKRYPTY set STATUS = 'T', DATA_END = sysdate 
	where SYSTEM = 'K2000_S' and skrypt = 'S061221_0';


commit; 